#!/usr/bin/env bash

# Function to get the subdomain information
get_subdomain_info() {
    local domain=$1
    local subdomain=$2

    lb_01_ip="54.172.103.134"
    web_01_ip="100.26.168.76"
    web_02_ip="100.25.36.82"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=($subdomain)
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig +short $sub.$domain | awk '{print $2}')
        destination=$(dig +short $sub.$domain)

        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

# Main script
if [ "$#" -eq 1 ]; then
    get_subdomain_info $1
elif [ "$#" -eq 2 ]; then
    get_subdomain_info $1 $2
else
    echo "Invalid number of arguments. Please provide domain and optionally subdomain."
fi
