#!/usr/bin/env bash

frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/example.com/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

backend www-backend
    balance serverbalance
    redirect scheme https if !{ ssl_fc}
    server 332194-web-01 100.26.168.76:80 check
    server 332194-web-02 100.25.36.82:80 check
