#!/usr/bin/env bash

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend 
    bind   0.0.0.0:80
    reqadd X-Forwarded-Proto:\ http
    default_backend 
    redirect scheme  code 301 if !{ ssl_fc }

frontend s
    bind   0.0.0.0:443 ssl crt /etc/haproxy/certs/
    reqadd X-Forwarded-Proto:\ 
    acl    letsencrypt-acl path_beg /.well-known/acme-challenge/
    use_backend letsencrypt-backend if letsencrypt-acl
    default_backend 


backend 
    balance  roundrobin
    redirect scheme  if !{ ssl_fc }
    server 332194-web-01 100.26.168.76:80 check
    server 332194-web-02 100.25.36.82:80 check

backend letsencrypt-backend
    server letsencrypt 127.0.0.1:54321
