#!/usr/bin/env bash
# Installs, configures, and starts the server
# serve a page returning hello world string

echo -e "updating and installing Nginx.\n"
sudo apt-get update
sudo apt-get install -y nginx


sudo chown -R ubuntu /var/www

#creating new index
echo "Hello World" > /var/www/html/index.nginx-debian.html

#restarting nginx
sudo service nginx start
