#!/usr/bin/env bash
# Set up server to curl port 80 with no issues

sudo apt-get update && sudo apt-get install -y nginx
echo "listen 0.0.0.0:80 default_server;" | sudo tee /etc/nginx/sites-available/default
sudo systemctl enable nginx
sudo systemctl restart nginx
