#!/usr/bin/env bash

# Update and install Nginx if it is not already installed
sudo apt-get update -y
sudo apt-get install -y nginx

# Ensure Nginx is set to listen on all active IPv4 IPs on port 80
sudo sed -i '/listen \[::\]:80 default_server;/d' /etc/nginx/sites-available/default
sudo sed -i 's/listen 80 default_server;/listen 0.0.0.0:80 default_server;/g' /etc/nginx/sites-available/default

# Ensure Nginx is enabled and running
sudo systemctl enable nginx
sudo systemctl start nginx
sudo systemctl restart nginx

# Check if Nginx is properly listening on port 80
if netstat -plnt | grep ':80'; then
    echo "Nginx is now listening on port 80"
else
    echo "There was an issue starting Nginx on port 80"
fi

