#!/usr/bin/env bash
# bash scripts to fulfill requirements
pid_file="/var/run/myscript.pid"

# Function to handle signals
signal_handler() {
    case $1 in
        SIGTERM)
            echo "I hate the kill command"
            ;;
        SIGINT)
            echo "Y U no love me?!"
            ;;
        SIGQUIT)
            clean_up
            ;;
    esac
}

# Function to clean up and terminate the script
clean_up() {
    rm -f "$pid_file"
    echo "Terminating the script"
    exit 0
}

# Trap signals
trap 'signal_handler SIGTERM' SIGTERM
trap 'signal_handler SIGINT' SIGINT
trap 'signal_handler SIGQUIT' SIGQUIT

# Create the PID file
echo $$ > "$pid_file"

# Display "To infinity and beyond" indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 1
done
