#!/usr/bin/env bash
#Bash script that stops 4-to_infinity_and_beyond process
# Find the PID of the process named "4-to_infinity_and_beyond" and stop it
pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$pid" ]; then
    kill "$pid"
    echo "Process 4-to_infinity_and_beyond stopped."
else
    echo "Process 4-to_infinity_and_beyond not found."
fi
