#!/usr/bin/env bash
#67-stop_me_if_you_can, that kills the 7-highlander process
# Find the PID of the process named "7-highlander" and stop it
pid=$(pgrep -f "7-highlander")
if [ -n "$pid" ]; then
    echo "Stopping process 7-highlander..."
    kill -15 "$pid"
    sleep 5
    if ps -p "$pid" > /dev/null; then
        echo "Forcefully stopping process 7-highlander..."
        kill -9 "$pid"
    fi
else
    echo "Process 7-highlander not found."
fi
