#!/usr/bin/env bash
# displays the content of the file /etc/passwd
# Using the IFS to read the file fields correctly
while IFS=: read -r username _ userid _ _ home _; do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $home"
done < /etc/passwd
