#!/usr/bin/env bash
#displays the content of the file /etc/passwd, using the while loop + IFS
# Using the IFS to read the file fields correctly
while IFS=: read -r username _ userid groupid _ info home shell; do
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode $info, more info about the user here: $userid INFO"
done < /etc/passwd
