#!/usr/bin/env bash
#displays the visitor IP along with the HTTP status code from Apache log file
# Using awk to extract IP and HTTP status code from the Apache log file
awk '{print $1, $9}' apache-access.log
