#!/usr/bin/env bash
#display content of the current directory
for file in *; do
    if [ -f "$file" ] && [[ "$file" != .* ]];
    then
        filename=$(echo "$file" | cut -d'-' -f2-)
        echo "$filename"
    fi
done
