#!/usr/bin/env bash
#Bash script that gives you information about the school file
FILE="school"
if [ -e $FILE ]
then
    echo "$FILE school file exists"
    if [ -s $FILE ]
    then
        echo "$FILE school file is not empty"
    else
        echo "$FILE school file is empty"
    fi
    if [ -f $FILE ]
    then
        echo "$FILE school is a regular file"
    fi
else
    echo "$FILE school file does not exist"
fi
