#!/usr/bin/env bash
# Configures an Ubuntu server with resolving requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

# Create a backup of the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Modify the hosts file to resolve localhost and facebook.com
sudo sh -c 'echo "127.0.0.2         localhost" > /etc/hosts.new'
sudo sh -c 'echo "8.8.8.8           facebook.com" >> /etc/hosts.new'

# Move the modified hosts file to /etc/hosts
sudo mv /etc/hosts.new /etc/hosts
