#!/usr/bin/env bash
# Configures an Ubuntu server with resolving requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

# Create a backup of the original hosts file
cp /etc/hosts /etc/hosts.bak

# Modify the hosts file to resolve localhost and facebook.com
echo "127.0.0.2         localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8           facebook.com" | sudo tee -a /etc/hosts
