#!/usr/bin/env bash
# Creates an RSA key pair

# Define the passphrase
passphrase="betty"

# Create an RSA key pair with the specified requirements
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N $passphrase
